### ISSUE TITLE
建议开发docker支持

### ISSUE THREAD

**Issue by rsun-thoughtworks** [icymind/VRouter#90]
特别说明下，现在docker已经很成熟了，是否考虑用docker来作为运行平台。

**Comment by hanxi** [comment]
应该可以实现,这里有个 openwrt 的 docker 镜像.https://hub.docker.com/r/nmaas87/docker-openwrt

docker 采用 macvlan 或者 ipvlan 可以实现虚拟机一样的桥接网卡.

**Comment by hanxi** [comment]
无线网卡用 ipvlan, 有线网卡可以用 macvlan. 希望哪位大佬可以试试构建一个镜像出来. 下面是 docker-compose 配置 ipvlan 的格式.

```yaml
version: '2'
  vrouter-gateway:
    image: vrouter-gateway
    restart: always
    container_name: vrouter-gateway
    hostname: vrouter-gateway
    privileged: true
    environment:
      - TZ:Asia/Shanghai
    networks:
      ipvlan:
        ipv4_address: "192.168.2.3"

networks:
  ipvlan:
    driver: ipvlan
    driver_opts:
      parent: wlp0s20f3
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"

```
